### ISSUE TITLE
Update locators 

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#10]
Update date locators to match changes on Treeherder: https://github.com/mozilla/treeherder/pull/740#event-353266060

**Comment by tojonmz** [comment]
I'll have a look at this with a local treeherder instance w/master, in case the changes in https://github.com/mozilla/treeherder/pull/740 aren't pushed to stage for a bit.

**Comment by tojonmz** [comment]
Independent of this change, it appears running py.test against a local server in the form `--baseurl=http://local.treeherder.mozilla.org` (vagrant) or `--baseurl=http://localhost:8000` (web-server.js) and/or `--port=8000`, seems to leave the tests hanging at the point at which it issues the send_keys 'n' to navigate to the first unclassified failure, which I've confirmed exists on the page.

Whereas with `--baseurl=https://treeherder.allizom.org` the tests run fine.

I'll poke around more next week.

Otherwise when we push the latest treeherder to stage this PR can be tested there :)

**Comment by rbillings** [comment]
The issue with running tests on a local server is a known issue, and should [hopefully] be resolved by the work @davehunt is doing to rewrite pytest-mozwebqa -> pytest-selenium. I'll close this as the locators were successfully updated.
